###############################################################################
## A. General Parameters 
###############################################################################

system:
  tf_seed: 11
  white_bg: False # Setting to True is only supported for BlenderDataset!
  run_eagerly: False
  log_images: False
  steps_per_epoch: 32
  validation_freq: 100
  tensorboard_dir: "./logs"
  initial_epoch: 0
  dataset_type: "CustomDataset" # One among "BlenderDataset" or "CustomDataset"

eval:
  save_dir: "/home/br7/Downloads/out"

render:
  radius: 5.0
  inclination: 50
  num_cameras: 30
  img_size: [800, 800] # [H, W]
  camera_model_name: "" # TODO: Fill
  camera_model_params: [] # TODO: Fill
  bounds: null # If null, bounds are auto calcualted.
  save_dir: ""

###############################################################################
## B. Model Functionality Related Parameters
###############################################################################

model:
  save:
    save_dir: "../expt_211023/save_dir/model" # "/content/drive/MyDrive/NerfExpts/save_dir/model"
    save_optimizer_state: True
  
  load:
    load_dir: "/home/br7/Downloads/test"
    load_tag: "013999_27.65"
    set_weights: True
    skip_optimizer: True

###############################################################################
## C. Data Parameters
###############################################################################

data:
  
  save_scene_metadata:
    # If save_dir is set to null, then the reconfig parameters will not be saved.
    save_dir: "../expt_211023/save_dir/reconfig"
    # If save_poses is set to False, then poses will not be saved.
    save_poses: False

  # scale_imgs can either be set to null or a float value. If scale_imgs 
  # is null, no scaling is applied. If scale_imgs is a float value, then 
  # the images and the intrinsic matrices are scaled.
  scale_imgs: 0.5

  scene_scale_mul: 0.75
  scene_scale_add: 0.0
  
  batch_size: 4096
  dataset_mode: "iterate" # One among "iterate" or "sample"

  # Parameters specific to dataset_mode "sample"
  sample_mode:
    shuffle_buffer_size: 20
    prefetch_buffer_size: 20
    repeat_count: 5000

  # Parameters specific to dataset_mode "iterate"
  iterate_mode:
    repeat_count: 36
    
    ## TODO: Give this parameter a better name.
    train_shuffle:
      enable: True
      seed: 35 

    advance_train_loader:
      enable: False
      skip_count: 0 # epochs * steps_per_epoch

###############################################################################
## D1. Blender Dataset Parameters (Only required if using BlenderDataset)
###############################################################################

blender_dataset:
  base_dir: ../lego

  shuffle:
    enable: ["train"]
    seed: 83

  val:
    num: 3
    frac: null
  
  test:
    num: 3
    frac: null

###############################################################################
## D2. Custom Dataset Parameters (Only required if using CustomDataset)
###############################################################################

custom_dataset:
  shuffle:
    enable: ["train"]
    seed: 83

  train:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv

  val:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv
    num: 3
    frac: null

  test:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv
    num: 3
    frac: null

###############################################################################
## E. Miscellaneous Parameters
###############################################################################

preprocessing:
  origin_method: "min_dist_solve"
  bounds_method: "include_corners"
  basis_method: "identity"

sampling:
  N_coarse: 64
  N_fine: 128
  perturb: True
  lin_inv_depth: False
