###############################################################################
## A. General Parameters 
###############################################################################

system:
  tf_seed: 11
  white_bg: False
  run_eagerly: False
  log_images: False
  steps_per_epoch: 32
  validation_freq: 100
  tensorboard_dir: "./logs"
  initial_epoch: 0

###############################################################################
## B. Model Functionality Related Parameters
###############################################################################

model:
  save:
    save_dir: "./models"
    save_optimizer_state: True
  
  load:
    load_dir: "./trained_models"
    load_tag: "000999_21.12"
    set_weights: False
    skip_optimizer: False

###############################################################################
## C. Data Parameters
###############################################################################

data:
  batch_size: 4096
  repeat_count: 20
  
  # scale_imgs can either be set to null or a float value. If scale_imgs 
  # is null, no scaling is applied. If scale_imgs is a float value, then 
  # the images and the intrinsic matrices are scaled.
  scale_imgs: 0.5

  advance_train_loader:
    enable: False
    skip_count: 32000 # epochs * steps_per_epoch

###############################################################################
## D1. Blender Dataset Parameters (Only required if using BlenderDataset)
###############################################################################

blender_dataset:
  base_dir: /path/to/base/dir

  shuffle:
    enable: ["train", "test", "val"]
    seed: 83

  val:
    num:
    frac:
  
  test:
    num:
    frac:

###############################################################################
## D2. Custom Dataset Parameters (Only required if using CustomDataset)
###############################################################################

custom_dataset:
  full:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv

###############################################################################
## E. Miscellaneous Parameters
###############################################################################

preprocessing:
  origin_method: "min_dist_solve"

sampling:
  N_coarse: 64
  N_fine: 128
  perturb: True
  lin_inv_depth: True
