## TODO: Complete this file and add comments.

data:
  batch_size: 1024
  
  # scale_imgs can either be set to null or a float value. If scale_imgs is null, no scaling is applied. 
  # If scale_imgs is a float value, then the images and the intrinsic matrices are scaled.
  scale_imgs: null
  
  pre_shuffle: True
  pre_shuffle_seed: 93

  # Validation data pipeline is different from the training data pipeline.
  validation:
    num_imgs: 3
    frac_imgs: null

  custom_dataset:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv

preprocessing:
  origin_method: "average"

sampling:
  N_coarse: 64
  N_fine: 64
  lindisp: False
  perturb: True

model:
  save_path: "./dummy.h5"
