## TODO: Complete this file and add comments.

data:
  batch_size: 5
  pre_shuffle: True
  pre_shuffle_seed: 93

  custom_dataset:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv

preprocessing:
  origin_method: "average"

sampling:
  N_coarse: 64
  N_fine: 64
  lindisp: False
  perturb: True
