###############################################################################
## A. General Parameters 
###############################################################################

system:
  tf_seed: 11
  white_bg: False
  run_eagerly: False
  log_images: True
  steps_per_epoch: 128
  validation_freq: 100
  tensorboard_dir: "./logs"

###############################################################################
## B. Model Functionality Related Parameters
###############################################################################

model:
  save:
    save_dir: "./models"
    save_optimizer_state: True
  
  load:
    load_dir: "./models"
    load_tag: "check"
    set_weights: False
    skip_optimizer: False

###############################################################################
## C. Data Parameters
###############################################################################

data:
  batch_size: 1024
  repeat_count: 5
  
  # scale_imgs can either be set to null or a float value. If scale_imgs 
  # is null, no scaling is applied. If scale_imgs is a float value, then 
  # the images and the intrinsic matrices are scaled.
  scale_imgs: null
  
  pre_shuffle: True
  pre_shuffle_seed: 93

  # Validation data pipeline is different from the training data pipeline.
  validation:
    num_imgs: 3
    frac_imgs: null

  custom_dataset:
    img_root_dir: ../data/images
    pose_info_path: ../data/pose_info.csv

###############################################################################
## D. Miscellaneous Parameters
###############################################################################

preprocessing:
  origin_method: "min_dist_solve"

sampling:
  N_coarse: 64
  N_fine: 64
  lindisp: False
  perturb: True
